Add base impl of inventory service

diff --git a/.github/workflows/lint-reusable.yml b/.github/workflows/lint-reusable.yml
--- a/.github/workflows/lint-reusable.yml
+++ b/.github/workflows/lint-reusable.yml
@@ -28,7 +28,7 @@ jobs:
           go-version: ${{ inputs.go-version }}
 
       - name: Show go.work (debug)
-        run: cat go.work || echo "❗ go.work not found"
+        run: cat go.work || echo "go.work not found"
 
       - name: Install Task
         uses: arduino/setup-task@v2.0.0
